using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DropMeteors : MonoBehaviour
{
    public GameObject meteor;
    public Vector3 meteorPosition;
    public float frequency;

    private float frequencyCounter = 0;
    // Update is called once per frame
    void Update()
    {
        if (frequencyCounter < 0)
        {
            Instantiate(meteor, meteorPosition, Quaternion.identity);
            frequencyCounter = frequency;
        }

        frequencyCounter -= Time.deltaTime;
    }
}
